title: Productled Docs
description: Enabling products to thrive in AARRR Pirate Metrics (Acquisition, Activation, Revenue, Retention and Referrals)
theme: just-the-docs

url: https://99x-incubator.github.io/productled/

aux_links:
  GitHub Repository: https://github.com/99x-incubator/productled
